version: '3.8'

services:
  grpc-service:
    build:
      context: ./grpc-service
    ports:
      - "50051:50051"
      - "9090:9090"
    depends_on:
      - rabbitmq

  python-client:
    build:
      context: ./python-client
    depends_on:
      - grpc-service
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672" # RabbitMQ management UI
      - "5672:5672"   # RabbitMQ AMQP port

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    depends_on:
      - grpc-service

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus